\input texinfo @c -*-texinfo-*-

@c %**start of header
@setfilename festvox.info
@settitle Building Voices in the Festival Speech Synthesis System
@finalout
@setchapternewpage odd
@c %**end of header
@c @pagesizes 200mm,150mm

@set EDITION 1.3:current
@set VERSION 1.4.1
@set UPDATED 28th July 2000

@ifinfo
This file documents the processes and issues in building
new voices in the @code{Festival} Speech Synthesis System a general
text-to-speech system.

Copyright (C) 1998-2000, Alan W Black and Kevin A. Lenzo.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX, or otherwise and
print the results, provided the printed document carries copying
permission notice identical to this one except for the removal of this
paragraph (this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the authors.
@end ifinfo

@titlepage
@title Building Voices in 
@title the Festival Speech Synthesis System
@subtitle Processes and issues in building speech synthesis voices
@subtitle Edition @value{EDITION}, for Festival Version @value{VERSION}
@subtitle @value{UPDATED}
@author by Alan W Black and Kevin A. Lenzo
@author Carnegie Mellon University

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1998-2000 Alan W Black and Kevin A. Lenzo, all rights
reserved.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the authors
@end titlepage

@node Top, , , (dir)

@menu
* Abstract::            initial comments
* Copying::             Copying, use and acknowledgements
* Introduction::        Goals and outline of document
General concepts
* Speech and Speech Synthesis::
* Festival Speech Synthesis System::
* Scheme programming::
* Utterances::
Building waveform synthesizers
* Waveform Synthesis::
* Diphone databases::   Diphone schema, recording and labelling
* Unit selection databases:: General unit selection models (clunits)
* Limited domain synthesis::
Building speaker specific prosodic models
* Building prosodic models::
* Lexicons::            Lexicons, letter-to-sound rules and post-lexical rules
* Text analysis::       Homographs, token to word rules
* General::             Some general issues
* Full example::        
* Evaluation::          Does it actually work and making it better
* Resources::           Getting more help, tools, data etc
* English phone lists:: How to pronounce English phones
* References::
* Index::               
@end menu

@node Abstract, Copying, , Top
@chapter Abstract

This document provides documentation for the processes and
issues in building a new voice in the Festival Speech
Synthesis System.  This covers the necessary stages in building
a voice either in an already supported language or in a completely
new language.

Although the task of building very high quality, general text-to-speech
(TTS) voices is still a difficult one, with many open research
questions, we believe the building of reasonable quality voices for many
tasks can be done with the information provided within this document.  A
number of different languages and voices have already been implemented
under Festival, including: US and UK English, Castillian and Mexican
Spanish, German, Polish, Greek, Welsh Gaelic, and Basque.  These were
often built in a short time, some in a just few weeks, by people
starting with only a little knowledge of speech synthesis.  Although the
quality varies, all have produced text-to-speech synthesizers capable of
reading text, like online newspapers, at a level that native speakers
can easily follow.

This document, and related scripts and examples, is often updated.
You should check the latest status at @url{http://www.festvox.org}.

This document specifically offers
@itemize @bullet
@item Support for designing, recording and autolabelling diphone databases
@item Support for designing, recording and autolabelling unit selection 
databases
@item Building simple limited domain synthesis engines
@item Support for building rule driven and data driven prosody models
duration, intonation and phrasing)
@item Support for building rule driven and data driven text analysis
@item Lexicon and building letter-to-sound rule support
@item Predefined scripts for building new US (and UK) English voices
@end itemize

Note that this document is not a manual for the Festival Speech
Synthesis System itself, and we assume that the user has access to the
Festival system and the Edinburgh Speech Tools.  Except where explicitly
mentioned constructing voices can be done using these tools alone.

The latest details, and a full software distribution of the Festival
Speech Synthesis System with related documents and resources, are
available through the home page at
@url{http://www.cstr.ed.ac.uk/projects/festival.html}

@node Copying, Introduction, Abstract, Top
@include copy.texi

@node Introduction, Utterances, Copying, Top
@include intro.texi

@node Speech and Speech Synthesis, Festival Speech Synthesis Systems, Introduction, Top
@include speech.texi

@node Festival Speech Synthesis System, Scheme programming, Introduction, Top
@include festival.texi

@node Scheme programming, Utterances, Festival Speech Synthesis System, Top
@include scheme.texi

@node Utterances, Diphone databases, Scheme programming, Top
@include utt.texi

@node Waveform Synthesis, Diphone databases, Utterances, Top
@include waveform.texi

@node Diphone databases, Unit selection databases, Waveform Synthesis, Top
@include diphone.texi

@node Unit selection databases, Limited domain synthesis, Diphone databases, Top
@include unitsel.texi

@node Limited domain synthesis, Building prosodic models, Unit selection databases, Top
@include ldom.texi

@node Building prosodic models, Lexicons, Limited domain synthesis, Top
@include prosody.texi

@node Lexicons, Text analysis, Building prosodic models, Top
@include lexicons.texi

@node Text analysis, General, Lexicons, Top
@include text.texi

@node General, Full example, Text analysis, Top
@include general.texi

@node Full example, Evaluation, General, Top
@include exam.texi

@node Evaluation, Resources, Full example, Top
@include eval.texi

@node Resources, English phone lists, Evaluation, Top
@include resources.texi

@node English phone lists, References, Resources, Top
@include phonetable.texi

@node References, Index, English phone lists, Top
@include refs.texi

@node Index, References, Top
@unnumbered Index

@printindex cp

@contents

@bye
