@chapter English phone lists

@menu
* US phoneset::
* UK phoneset::
@end menu

Relating phonemes to sounds is not obvious as people think.  Even when
one is familar with phone sets its easy to make mistakes when reading
lists of phones alone.  This is particularly true in reading diphone
nonsense words.  The table provided here are intended for both the
experienced and inexperienced reader of phones, to help you decide
on the pronunciation.

These tables are not supposed to be a substitute for a good phonetics
course, they are intended to give people a basic idea of the
pronunciation of the phone sets used in the particaulr examples in this
document.  Many simplifying assumptions have been made, and often aren't
even mentioned.  To the phoneticians out there I apologise, as much as
the assumptions are wrong we are here listing atomic discrete phones
which we have found useful in building practical systems, even though
better sets probably exist.

@node US phoneset, UK phoneset, , English phone lists
@section US phoneset

Inspite of everyone telling you that there is one and only one US
phoneset, when it comes to actually using one you quickly discover there
are actually many standard one used by lots of different pieces of
software, often the difference betwen them is trivial (e.g. case
folding) but computers being fundamentally dumb can't take
these trivial differences into account.  Here we list the
@emph{radio} phoneset which is used by standard US voices in
festival.  The definition is in @file{festival/lib/radio_phones.scm}.
This list was based on those phones that appear in the Boston
University FM radio corpus with minor modifications.  The
list here is exactly those phones which appear in the diphone
nonses words as used in the example explained in 
@ref{US/UK English Walkthrough}.
@table @emph
@item aa
fAther, wAshington
@item ae
fAt, bAd
@item ah 
bUt, hUsh
@item ao
lAWn, dOOr, mAll
@item aw
hOW, sOUth, brOWser
@item ax
About, cAnoe
@item ay
hIde, bIble
@item eh
gEt, fEAther
@item el
tabLE, usabLE
@item em
systEM, communisM
@item en
beatEN
@item er
fERtile, sEARch, makER
@item ey
gAte, Ate
@item ih
bIt, shIp
@item iy
bEAt, shEEp
@item ow
lOne, nOse
@item oy
tOY, OYster
@item uh
fUll, wOOd
@item uw
fOOl, fOOd
@item b
Book, aBrupt
@item ch 
CHart, larCH
@item d
Done, baD
@item dh
THat, faTHer
@item f
Fat, lauGH
@item g
Good, biGGer
@item hh
Hello, loopHole
@item jh
diGit, Jack
@item k
Camera, jaCK, Kill
@item l
Late, fuLL
@item m
Man, gaMe
@item n
maN, New
@item ng
baNG, sittiNG
@item p
Pat, camPer
@item r
Reason, caR,
@item s
Sit, maSS
@item sh
SHip, claSH
@item t
Tap, baT
@item th
THeatre, baTH
@item v
Various, haVe
@item w
Water, cobWeb
@item y
Yellow, Yacht
@item z
Zero, quiZ, boyS
@item zh
viSion, caSual
@item pau
short silence
@end table
In addition to the phone sthemselves the nonsense word generated by
the diphone schema also have some other notations to denote different
type of phone.

The use of @emph{-} (hyphen) in the nonsense word itself is used to denot
an explicit syllable boundary.  Thus @code{pau t aa n - k aa pau}
is used to state that the word should be pronounced as @code{tan ka}
rather than @code{tank ah}.  Where no explicit syllable boundary
is given the pronunciation should be pronounce naturally without
any boundary (which is probabaly too underspecified in some cases).

The use of @emph{_} (underscore) in phone names is used to denote
consonant clusters.  That is @code{t_-_r} is the /tr/ as found
in @code{trip} not that in @code{cat run}.

@node UK phoneset, , US phoneset, English phone lists
@section UK phoneset

This phoneset developed at CSTR a number of years ago is for 
Southern UK English (RP, "received pronunciation").  Its
definition is in @file{festival/lib/mrpa_phones.scm}.
@table @emph
@item uh
cUp, dOne
@item e
bEt, chEck
@item a
cAt, mAtch
@item o
cOttage, hOt
@item i
bIt, shIp
@item u
pUll, fOOt, bOOk
@item ii
bEAt, shEEp
@item uu
pOOl, bOOt
@item oo
AUthor, cOURt
@item aa
ARt, hEARt
@item @@@@
sEARch, bURn
@item ai
bIte, mIght, lIke
@item ei
Ate, mAIl
@item oi
tOY, OYster
@item au
sOUth, hOW
@item ou
hOle, cOAt
@item e@@
AIR, bARE, chAIR
@item i@@
EAR, bEER
@item u@@
sUre, jUry
@item @@
About, arlAs, equipmEnt
@item p
Pat, camPer
@item t
Tap, baT
@item k
Camera, jaCK, Kill
@item b
Book, aBrupt
@item d
Done, baD
@item g
Good, biGGer
@item s
Sit, maSS
@item z
Zero, quiZ, boyS
@item sh
SHip, claSH
@item zh
viSion, caSual
@item f
Fat, lauGH
@item v
Various, haVe
@item th
THeatre, baTH
@item dh
THat, faTHer
@item ch 
CHart, larCH
@item jh
diGit, Jack
@item h
Hello, loopHole
@item m
Man, gaMe
@item n
maN, New
@item ng
baNG, sittiNG
@item l
Late, bLack
@item y
Yellow, Yacht
@item r
Reason, caReer,
@item w
Water, cobWeb
@item #
short silence
@end table

In addition to the phone sthemselves the nonsense word generated by
the diphone schema also have some other notations to denote different
type of phone.

The use of @emph{-} (hyphen) in the nonsense word itself is used to denot
an explicit syllable boundary.  Thus @code{pau t aa n - k aa pau}
is used to state that the word should be pronounced as @code{tan ka}
rather than @code{tank ah}.  Where no explicit syllable boundary
is given the pronunciation should be pronounce naturally without
any boundary (which is probabaly too underspecified in some cases).

The use of @emph{_} (underscore) in phone names is used to denote
consonant clusters.  That is @code{t_-_r} is the /tr/ as found
in @code{trip} not that in @code{cat run}.


