#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                   Carnegie Mellon University and                      ##
##                   Alan W Black and Kevin A. Lenzo                     ##
##                      Copyright (c) 1998-2000                          ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  Generate skeletal scm files for a diphone voice                      ##
##                                                                       ##
###########################################################################

if [ ! "$FESTVOXDIR" ]
then
   echo "environment variable FESTVOXDIR is unset"
   echo "set it to your local festvox directory e.g."
   echo '   bash$ export FESTVOXDIR=/home/awb/DOCS/reports/festvox/'
   echo or
   echo '   csh% setenv FESTVOXDIR /home/awb/DOCS/reports/festvox/'
   exit 1
fi

if [ $# != 3 ]
then
    echo "Build dirs, and setup scripts and scm files for a new diphone voice "
    echo "Usage: setup_diphone INST LANG VOX"
    echo "INST is the insstitute building the language, e.g. cmu, cstr, ogi"
    echo "     if there isn't an appropriate institute use, net."
    echo "LANG is language identifier, e.g. japan, scotsgaelic"
    echo "VOX is speaker identifier e.g kal, awb"
    exit 1
fi

FV_INST=$1
FV_LANG=$2
FV_VOX=$3
SKELFESTVOXDIR=$FESTVOXDIR/src/vox_diphone/festvox

# Build the directory structure
$FESTVOXDIR/src/general/make_dirs

# General utilities
cp -p $FESTVOXDIR/src/general/make_lpc bin
cp -p $FESTVOXDIR/src/general/make_pm bin
cp -p $FESTVOXDIR/src/general/make_pm_wave bin
cp -p $FESTVOXDIR/src/general/make_pm_lab bin
cp -p $FESTVOXDIR/src/diphones/make_labs bin
cp -p $FESTVOXDIR/src/diphones/make_diph_index bin
cp -p $FESTVOXDIR/src/diphones/prompt_them bin
cp -p $FESTVOXDIR/src/diphones/diphlist.scm bin
cp -p $FESTVOXDIR/src/general/emu_lab.tpl etc/emu_lab.tpl
cp -p $FESTVOXDIR/src/general/emu_pm.tpl etc/emu_pm.tpl

# Language/Vox scheme files
case $FV_LANG in
   us)
      echo "copying skeleton files for US English"
      for i in $SKELFESTVOXDIR/INST_us_VOX_*.scm
      do
         fname=`basename $i`
         newname=`echo $fname | sed 's/INST/'$FV_INST'/g' | sed 's/VOX/'$FV_VOX'/g'`
         cat $i | sed 's/INST/'$FV_INST'/g' | sed 's/VOX/'$FV_VOX'/g' >festvox/$newname
      done
      cp -p $FESTVOXDIR/src/diphones/us_schema.scm bin/us_schema.scm
      ;;
   uk)
      echo "copying skeleton files for UK English"
      for i in $SKELFESTVOXDIR/INST_uk_VOX_*.scm
      do
         fname=`basename $i`
         newname=`echo $fname | sed 's/INST/'$FV_INST'/g' | sed 's/VOX/'$FV_VOX'/g'`
         cat $i | sed 's/INST/'$FV_INST'/g' | sed 's/VOX/'$FV_VOX'/g' >festvox/$newname
      done
      cp -p $FESTVOXDIR/src/diphones/uk_schema.scm bin/uk_schema.scm
      ;;
   *)
      echo "copying skeleton files for new language: "$FV_LANG
      for i in $SKELFESTVOXDIR/INST_LANG_*.scm
      do
         fname=`basename $i`
         newname=`echo $fname | sed 's/INST/'$FV_INST'/g' | sed 's/LANG/'$FV_LANG'/g' | sed 's/VOX/'$FV_VOX'/g'`
         cat $i | sed 's/INST/'$FV_INST'/g' | sed 's/LANG/'$FV_LANG'/g' | sed 's/VOX/'$FV_VOX'/g' >festvox/$newname
      done
      if [ -f $FESTVOXDIR/src/diphones/$FV_LANG"_schema.scm" ]
      then
         cp -p $FESTVOXDIR/src/diphones/$FV_LANG"_schema.scm" bin
      fi
      ;;
esac





