#!/bin/sh
#####################################################-*-mode:shell-script-*-
###                                                                       ##
###                    Alan W Black and Kevin Lenzo                       ##
###                         Copyright (c) 1998                            ##
###                        All Rights Reserved.                           ##
###                                                                       ##
###  Permission to use, copy, modify,  and licence this software and its  ##
###  documentation for any purpose, is hereby granted without fee,        ##
###  subject to the following conditions:                                 ##
###   1. The code must retain the above copyright notice, this list of    ##
###      conditions and the following disclaimer.                         ##
###   2. Any modifications must be clearly marked as such.                ##
###   3. Original authors' names are not deleted.                         ##
###                                                                       ##
###  THE AUTHORS OF THIS WORK DISCLAIM ALL WARRANTIES WITH REGARD TO      ##
###  THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY   ##
###  AND FITNESS, IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY         ##
###  SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES            ##
###  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
###  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
###  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
###  THIS SOFTWARE.                                                       ##
###                                                                       ##
###  This file is part "Building Voices in the Festival Speech            ##
###  Synthesis System" by Alan W Black and Kevin Lenzo written at         ##
###  Robotics Institute, Carnegie Mellon University, fall 98              ##
############################################################################
###                                                                       ##
###  Generate cepstrum and F0 acoustic parameter files for unit selection ##
###                                                                       ##
############################################################################

if [ ! "$ESTDIR" ]
then
   echo "environment variable ESTDIR is unset"
   echo "set it to your local speech tools directory e.g."
   echo '   bash$ export ESTDIR=/home/awb/projects/speech_tools/'
   echo or
   echo '   csh% setenv ESTDIR /home/awb/projects/speech_tools/'
   exit 1
fi
PDA_PARAMS="-fmax 180 -fmin 80"
SIG2FV=$ESTDIR/bin/sig2fv
SIG2FVPARAMS='-coefs melcep -delta melcep -melcep_order 12 -fbank_order 24 -shift 0.01 -factor 2.5 -preemph 0.97'

if [ $# = 0 ]
then
   echo "Build cepstrum files for acoustic measures"
   echo "Usage:  bin/make_mcep wav/*.wav"
   echo "Will create cepstrum parameters files with F0 in 0 coefficient"
   echo "in festival/coeffs/*.dcoeffs, also F0 files will be generated"
   echo "in festival/f0/*.f0"
   exit 1
fi

if [ ! -f festival/coeffs ]
then
   mkdir festival/coeffs
fi

if [ ! -f festival/f0 ]
then
   mkdir festival/f0
fi

for i in $*
do
  fname=`basename $i .wav`
  echo $fname
  $SIG2FV $SIG2FVPARAMS -otype ascii $i -o /tmp/tmp.$$.ascii
  if [ ! -f festival/f0/$fname.f0 ]
  then
     $ESTDIR/bin/pda -s 0.01 -o festival/f0/$fname.f0 -otype ascii $PDA_PARAMS wav/$fname.wav
  fi
  $ESTDIR/bin/ch_track -pc first -itype ascii -s 0.010 -otype htk festival/f0/$fname.f0 /tmp/tmp.$$.ascii -o festival/coeffs/$fname.dcoeffs
  rm /tmp/tmp.$$.*
done


