#!/bin/sh
#####################################################-*-mode:shell-script-*-
###                                                                       ##
###                    Alan W Black and Kevin Lenzo                       ##
###                         Copyright (c) 1998                            ##
###                        All Rights Reserved.                           ##
###                                                                       ##
###  Permission to use, copy, modify,  and licence this software and its  ##
###  documentation for any purpose, is hereby granted without fee,        ##
###  subject to the following conditions:                                 ##
###   1. The code must retain the above copyright notice, this list of    ##
###      conditions and the following disclaimer.                         ##
###   2. Any modifications must be clearly marked as such.                ##
###   3. Original authors' names are not deleted.                         ##
###                                                                       ##
###  THE AUTHORS OF THIS WORK DISCLAIM ALL WARRANTIES WITH REGARD TO      ##
###  THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY   ##
###  AND FITNESS, IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY         ##
###  SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES            ##
###  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
###  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
###  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
###  THIS SOFTWARE.                                                       ##
###                                                                       ##
###  This file is part "Building Voices in the Festival Speech            ##
###  Synthesis System" by Alan W Black and Kevin Lenzo written at         ##
###  Robotics Institute, Carnegie Mellon University, fall 98              ##
############################################################################
###                                                                       ##
###  Make the directories assumes . is the db directory                   ##
###                                                                       ##
############################################################################

##
##  This make more directories than you may need
##

mkdir bin
mkdir wav
mkdir lab
mkdir lar
mkdir lpc
mkdir pm
mkdir wrd
mkdir dic
mkdir etc
mkdir festival
mkdir festival/relations
mkdir festival/relations/Segment
mkdir festival/relations/Phrase
mkdir festival/relations/Target
mkdir festival/relations/Syllable
mkdir festival/relations/Word
mkdir festival/relations/IntEvent
mkdir festival/utts
mkdir festival/coeffs
mkdir festival/f0
mkdir festival/disttabs
mkdir festival/trees
mkdir festival/feats
mkdir festival/clunits
mkdir festival/phrbrk
mkdir festival/dur
mkdir festival/accents
mkdir festvox
